name: Bug Report
description: Report a bug or unexpected behavior in the UI
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please fill out the form below to help us understand and fix the issue.

  - type: dropdown
    id: component
    attributes:
      label: Component/Page
      description: Which part of the UI is affected?
      options:
        - Authentication/Login
        - Chat Interface
        - Agent Creation/Management
        - Project/Repository Management
        - Workflow Builder
        - Settings/Configuration
        - Dashboard/Home
        - API Integration
        - Responsive Design/Mobile
        - Styling/Theming
        - Performance
        - Other
    validations:
      required: true

  - type: dropdown
    id: environment
    attributes:
      label: Environment
      description: Where is this bug occurring?
      options:
        - Local Development
        - Production
        - Both
    validations:
      required: true

  - type: dropdown
    id: severity
    attributes:
      label: Severity
      description: How severe is this bug?
      options:
        - Critical (App crashes/Unusable)
        - High (Major feature broken)
        - Medium (Feature partially broken)
        - Low (Minor issue/Cosmetic)
    validations:
      required: true

  - type: input
    id: browser
    attributes:
      label: Browser
      description: Which browser are you using?
      placeholder: "e.g., Chrome 120, Firefox 121, Safari 17"
    validations:
      required: true

  - type: input
    id: os
    attributes:
      label: Operating System
      description: Your operating system
      placeholder: "e.g., macOS 14.0, Ubuntu 22.04, Windows 11"
    validations:
      required: true

  - type: textarea
    id: environment_info
    attributes:
      label: Environment Information
      description: |
        Please provide relevant environment details:
        - Node.js version
        - pnpm version
        - Next.js version (if known)
        - Any relevant environment variables (sanitize sensitive data)
      placeholder: |
        Node.js: 20.10.0
        pnpm: 8.15.0
        Next.js: 14.0.0
        NEXT_PUBLIC_API_URL: http://localhost:8001
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: What happened?
      placeholder: A clear and concise description of what the bug is.
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What should have happened?
      placeholder: A clear and concise description of what you expected to happen.
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened?
      placeholder: A clear and concise description of what actually happened.
    validations:
      required: false

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Please provide numbered steps to reproduce the issue
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: false

  - type: textarea
    id: console_errors
    attributes:
      label: Browser Console Errors
      description: |
        Please paste any errors from the browser console (F12 → Console tab).
        Wrap code blocks with triple backticks (```).
      placeholder: |
        ```
        Paste console errors here
        ```
    validations:
      required: false
      render: shell

  - type: textarea
    id: network_errors
    attributes:
      label: Network Errors
      description: |
        Any failed API requests? Check the Network tab (F12 → Network).
        Include request URL, method, and response status if available.
      placeholder: |
        GET /api/v1/conversations/123 - 500 Internal Server Error
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other context, screenshots, or information about the problem
      placeholder: Add any other context about the problem here. Screenshots are especially helpful!
    validations:
      required: false

